version: "2"

services:

  proxy:
    restart: always
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ENABLE_IPV6=${ENABLE_IPV6}
  volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - ./ssl/:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  ssl-proxy:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes_from:
      - proxy
    volumes:
      - ./ssl/:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - proxy

  db:
    image: mariadb:10.2
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  app:
    image: piwik:3
    links:
      - db
    volumes:
      - ./config:/var/www/html/config
    #      - ./ssmtp.conf:/etc/ssmtp/ssmtp.conf
    #      - ./revaliases:/etc/ssmtp/revaliases
    depends_on:
      - db
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - HTTPS_METHOD=${HTTPS_METHOD}
  
  cron:
    image: piwik:3-fpm
    links:
      - db
    volumes_from:
      - app
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      while /bin/true; do
        su -s "/bin/bash" -c "/usr/local/bin/php /var/www/html/console core:archive" www-data
        sleep 3600
      done
      EOF'
